name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore dependencies
      run: dotnet restore ActionDemo.sln
    - name: Build
      run: dotnet build --no-restore ActionDemo.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ActionDemo.sln
